--- 
- 
  become: true
  hosts: all
  ignore_errors: true
  remote_user: ansible
  sudo: true
  tasks: 
    - 
      name: "upgrade all packages"
      yum: "name=* state=latest"
    - 
      ignore_errors: true
      name: "Check for reboot hint."
      register: reboot_hint
      shell: "LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,\"\"); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi"
    - 
      async: 0
      command: "shutdown -r now \"Reboot required for updated kernel\""
      ignore_errors: true
      name: "Rebooting ..."
      poll: 0
      register: rebooting
      sudo: true
      when: "reboot_hint.stdout.find(\"reboot\") != -1"
    - 
      name: "Wait for thing to reboot..."
      pause: seconds=45
      when: rebooting|changed
