--- 
- become: true
  hosts: all
  ignore_errors: true
  become_method: su
  
  tasks: 

  - name: delete all yum cache prior to patching
    file:
      path: /var/cache/yum
      state: directory
    become: yes
    ignore_errors: true

  - name: update the system
    yum:
     name: "*"
     state: latest
    become: yes
    ignore_errors: true

  - name: Restart server
    command: /sbin/reboot
    async: 0
    poll: 0
    ignore_errors: true
